#!/bin/sh
# Frontend entrypoint for docker-compose.
#
# Reason this exists:
#   When developers run `docker-compose up` on a laptop, the committed
#   `frontend/.env` still points EXPO_PUBLIC_BACKEND_URL to the Emergent
#   preview host. The browser is on localhost, so HTTP calls to that
#   external host fail. The browser case is handled at runtime by
#   `src/backend.ts` (it rewrites localhost -> http://localhost:8001).
#
#   But Expo Go on a phone has no `window`, so it MUST read the URL from
#   the bundle. To support that without editing the committed file, we
#   write a `.env.local` here (Expo loads .env.local BEFORE .env) so the
#   value is overridden inside the container only.
#
#   Set DOCKER_BACKEND_URL in the root `.env` (or shell env) to the URL
#   your phone/emulator can actually reach the backend on — typically the
#   LAN IP of the docker host, e.g. http://192.168.1.42:8001.
#   Falls back to http://localhost:8001 (works for web-on-same-machine).

set -e

cd /app

BACKEND_URL="${DOCKER_BACKEND_URL:-${EXPO_PUBLIC_BACKEND_URL:-http://localhost:8001}}"

cat > .env.local <<EOF
# AUTOGENERATED by docker-entrypoint.sh — DO NOT EDIT.
# Overrides .env values for this container only.
EXPO_PUBLIC_BACKEND_URL=${BACKEND_URL}
EOF

echo "[entrypoint] Wrote .env.local with EXPO_PUBLIC_BACKEND_URL=${BACKEND_URL}"

# Hand off to the real command
exec "$@"
